require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReceitasController do

  # This should return the minimal set of attributes required to create a valid
  # Receita. As you add validations to Receita, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nomereceita" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReceitasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all receitas as @receitas" do
      receita = Receita.create! valid_attributes
      get :index, {}, valid_session
      assigns(:receitas).should eq([receita])
    end
  end

  describe "GET show" do
    it "assigns the requested receita as @receita" do
      receita = Receita.create! valid_attributes
      get :show, {:id => receita.to_param}, valid_session
      assigns(:receita).should eq(receita)
    end
  end

  describe "GET new" do
    it "assigns a new receita as @receita" do
      get :new, {}, valid_session
      assigns(:receita).should be_a_new(Receita)
    end
  end

  describe "GET edit" do
    it "assigns the requested receita as @receita" do
      receita = Receita.create! valid_attributes
      get :edit, {:id => receita.to_param}, valid_session
      assigns(:receita).should eq(receita)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Receita" do
        expect {
          post :create, {:receita => valid_attributes}, valid_session
        }.to change(Receita, :count).by(1)
      end

      it "assigns a newly created receita as @receita" do
        post :create, {:receita => valid_attributes}, valid_session
        assigns(:receita).should be_a(Receita)
        assigns(:receita).should be_persisted
      end

      it "redirects to the created receita" do
        post :create, {:receita => valid_attributes}, valid_session
        response.should redirect_to(Receita.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved receita as @receita" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receita.any_instance.stub(:save).and_return(false)
        post :create, {:receita => { "nomereceita" => "invalid value" }}, valid_session
        assigns(:receita).should be_a_new(Receita)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Receita.any_instance.stub(:save).and_return(false)
        post :create, {:receita => { "nomereceita" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested receita" do
        receita = Receita.create! valid_attributes
        # Assuming there are no other receitas in the database, this
        # specifies that the Receita created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Receita.any_instance.should_receive(:update).with({ "nomereceita" => "MyString" })
        put :update, {:id => receita.to_param, :receita => { "nomereceita" => "MyString" }}, valid_session
      end

      it "assigns the requested receita as @receita" do
        receita = Receita.create! valid_attributes
        put :update, {:id => receita.to_param, :receita => valid_attributes}, valid_session
        assigns(:receita).should eq(receita)
      end

      it "redirects to the receita" do
        receita = Receita.create! valid_attributes
        put :update, {:id => receita.to_param, :receita => valid_attributes}, valid_session
        response.should redirect_to(receita)
      end
    end

    describe "with invalid params" do
      it "assigns the receita as @receita" do
        receita = Receita.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receita.any_instance.stub(:save).and_return(false)
        put :update, {:id => receita.to_param, :receita => { "nomereceita" => "invalid value" }}, valid_session
        assigns(:receita).should eq(receita)
      end

      it "re-renders the 'edit' template" do
        receita = Receita.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Receita.any_instance.stub(:save).and_return(false)
        put :update, {:id => receita.to_param, :receita => { "nomereceita" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested receita" do
      receita = Receita.create! valid_attributes
      expect {
        delete :destroy, {:id => receita.to_param}, valid_session
      }.to change(Receita, :count).by(-1)
    end

    it "redirects to the receitas list" do
      receita = Receita.create! valid_attributes
      delete :destroy, {:id => receita.to_param}, valid_session
      response.should redirect_to(receitas_url)
    end
  end

end
